name: movie_info
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  dio: ^5.7.0
  logger: ^2.4.0
  fan_carousel_image_slider: ^1.0.1
  buttons_tabbar: ^1.3.13
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.0.0
  shimmer: ^3.0.0
  google_nav_bar: ^5.0.7
  youtube_player_flutter: ^9.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  mockito: ^5.4.2
  build_runner: ^2.4.6
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/